services:
  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://ashutosh:ninja@cluster0.9bpa22r.mongodb.net/taskdb?retryWrites=true&w=majority
    restart: always

  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:5001/api
    ports:
      - "5174:5173"
    depends_on:
      - server
    restart: always
