name: build-and-lint
#define when this workflow should run
#trigger on push to these branches
on:
  push:
    branches: [main,master, dev]
  pull_request:
    branches: [main,master, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Backend
      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      # Client
      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint -- --max-warnings=0 

      - name: Build client
        working-directory: client
        run: npm run build   
